#ifndef _cfe_msgids_
#define _cfe_msgids_

#include "cfe_mission_cfg.h"

#define CFE_EVS_CMD_MID         CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_EVS_CMD_MSG         /* 0x1901 */
                                                       /* Message ID 0x1902 is available  */
#define CFE_SB_CMD_MID          CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_SB_CMD_MSG          /* 0x1903 */
#define CFE_TBL_CMD_MID         CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_TBL_CMD_MSG         /* 0x1904 */
#define CFE_TIME_CMD_MID        CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_TIME_CMD_MSG        /* 0x1905 */
#define CFE_ES_CMD_MID          CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_ES_CMD_MSG          /* 0x1906 */

#define CFE_ES_SEND_HK_MID      CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_ES_SEND_HK_MSG      /* 0x1908 */
#define CFE_EVS_SEND_HK_MID     CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_EVS_SEND_HK_MSG     /* 0x1909 */
                                                       /* Message ID 0x190A is available  */
#define CFE_SB_SEND_HK_MID      CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_SB_SEND_HK_MSG      /* 0x190B */
#define CFE_TBL_SEND_HK_MID     CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_TBL_SEND_HK_MSG     /* 0x190C */
#define CFE_TIME_SEND_HK_MID    CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_TIME_SEND_HK_MSG    /* 0x190D */

#define CFE_SB_SUB_RPT_CTRL_MID CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_SB_SUB_RPT_CTRL_MSG /* 0x190E */

#define CFE_TIME_TONE_CMD_MID   CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_TIME_TONE_CMD_MSG   /* 0x1910 */
#define CFE_TIME_1HZ_CMD_MID    CFE_MISSION_CMD_MID_BASE2 + CFE_MISSION_TIME_1HZ_CMD_MSG    /* 0x1911 */


/*
** cFE Global Command Message Id's
*/
#define CFE_TIME_DATA_CMD_MID   CFE_MISSION_CMD_MID_BASE_GLOB + CFE_MISSION_TIME_DATA_CMD_MSG   /* 0x1960 */
#define CFE_TIME_SEND_CMD_MID   CFE_MISSION_CMD_MID_BASE_GLOB + CFE_MISSION_TIME_SEND_CMD_MSG   /* 0x1962 */


/*
** CFE Telemetry Message Id's
*/
#define CFE_ES_HK_TLM_MID           CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_ES_HK_TLM_MSG       /* 0x0900 */
#define CFE_EVS_HK_TLM_MID          CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_EVS_HK_TLM_MSG      /* 0x0901 */
                                                       /* Message ID 0x0902 is available  */
#define CFE_SB_HK_TLM_MID           CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_SB_HK_TLM_MSG       /* 0x0903 */
#define CFE_TBL_HK_TLM_MID          CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_TBL_HK_TLM_MSG      /* 0x0904 */
#define CFE_TIME_HK_TLM_MID         CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_TIME_HK_TLM_MSG     /* 0x0905 */
#define CFE_TIME_DIAG_TLM_MID       CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_TIME_DIAG_TLM_MSG   /* 0x0906 */
#define CFE_EVS_LONG_EVENT_MSG_MID  CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_EVS_LONG_EVENT_MSG_MSG   /* 0x0908 */
#define CFE_EVS_SHORT_EVENT_MSG_MID CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_EVS_SHORT_EVENT_MSG_MSG  /* 0x0909 */
#define CFE_SB_STATS_TLM_MID        CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_SB_STATS_TLM_MSG    /* 0x090A */
#define CFE_ES_APP_TLM_MID          CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_ES_APP_TLM_MSG      /* 0x090B */
#define CFE_TBL_REG_TLM_MID         CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_TBL_REG_TLM_MSG     /* 0x090C */
#define CFE_SB_ALLSUBS_TLM_MID      CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_SB_ALLSUBS_TLM_MSG  /* 0x090D */
#define CFE_SB_ONESUB_TLM_MID       CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_SB_ONESUB_TLM_MSG   /* 0x090E */

#ifndef CFE_OMIT_DEPRECATED_6_7
  #define CFE_ES_SHELL_TLM_MID        CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_ES_SHELL_TLM_MSG    /* 0x090F */
#endif

#define CFE_ES_MEMSTATS_TLM_MID     CFE_MISSION_TLM_MID_BASE2 + CFE_MISSION_ES_MEMSTATS_TLM_MSG /* 0x0910 */

/*
 * MID definitions by these older names are required to make some existing apps compile
 * These are deprecated and should be removed after CFE 6.6
 */
#ifndef CFE_OMIT_DEPRECATED_6_6

#define CFE_EVS_EVENT_MSG_MID        CFE_EVS_LONG_EVENT_MSG_MID

#endif

#endif
