#!/usr/bin/env python3

import socket, struct, optparse, sys

parser = optparse.OptionParser('sends CCSDS packets to CI')
parser.add_option('--host', action='store', dest='host', default='127.0.0.1', help='Host name/IP address of the CI host.')
parser.add_option('--port', type='int', dest='port', default=1234, help='Port of the CI host.')
parser.add_option('--mid', type='int', dest='mid', default=0x18FA, help='Message ID.')
parser.add_option('--cc', type='int', dest='cc', default=0, help='Command code.')
(options, args) = parser.parse_args()

payload=sys.stdin.buffer.read()

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

ccsds_msg = struct.pack('>HHHBB', options.mid, 0, len(payload) + 1, options.cc, 0) + payload

print('sending %r' % ccsds_msg)

sock.sendto(ccsds_msg, (options.host, options.port))
