#!/bin/bash -e

if [ $# -lt 1 ]; then
    echo "Usage: $0 <CFS_FOLDER>"
    exit 1
fi
CFS_ROOT="$1"

pids=""
for cpu in cpu1 cpu2 cpu3
do
    echo starting ${cpu}
    pushd ${CFS_ROOT}/build/exe/${cpu}
    ./core-${cpu} -R PO 2>&1 > ${cpu}.log &
    pids="${pids} $!"
    popd
    sleep 1
done

echo waiting for SBN network to settle
sleep 5

echo starting to_recv
./to_recv 2>&1 > to_recv.log &
pids="${pids} $!"
tail -f to_recv.log &
pids="${pids} $!"
sleep 5

echo starting TO
TO_MID=0x1880
TO_START_CC=6
printf '127.0.0.1       ' | ./cisend --mid=$TO_MID --cc=$TO_START_CC
sleep 1

echo commanding Fib
FIB_MID=0x1882
printf '' | ./cisend --mid=$FIB_MID --cc=0
sleep 1
printf '' | ./cisend --mid=$FIB_MID --cc=0
sleep 1
printf '' | ./cisend --mid=$FIB_MID --cc=0
sleep 1

echo -n "Press return to shut down: "
read

for pid in $pids
do
    kill $pid
done

echo done
